--Melinoe effects
local file = rom.path.combine(rom.paths.Content, 'Game/Animations/Melinoe_1Base_VFX.sjson')
sjson.hook(file, function(data)
	table.insert(data.Animations,
		{
		Name = "ChronosBlinkStreak",
		InheritFrom = "BlinkStreak",
		AddColor = true,
		ColorFromOwner = "Ignore",
		StartRed = 1,
		StartGreen = 1,
		StartBlue = 0.8,
		EndRed = 0.6,
		EndGreen = 0.6,
		EndBlue = 0.0 ,
		ClearCreateAnimations = true,
	})

    table.insert(data.Animations,
    {
        Name = "ChronosBlinkTrailFxOutGroundLighting",
        InheritFrom = "BlinkTrailFxOutGroundLighting",
        Red = 0.6,
		Green = 0.6,
		Blue = 0,
    })

    table.insert(data.Animations,
    {
        Name = "ChronosBlinkTrailFxOut",
        InheritFrom = "BlinkTrailFxOut",
        AddColor = true,
        ColorFromOwner = "Ignore",
        StartRed = 1,
        StartGreen = 1,
        StartBlue = 0.8,
        EndRed = 0.6,
        EndGreen = 0.6,
        EndBlue = 0.0,
        ClearCreateAnimations = true,
        CreateAnimations =
        {
            { Name = "ChronosBlinkTrailFxOutGroundLighting", },
        },
	})

    table.insert(data.Animations,
    {
        Name = "ChronosBlinkTrailFxLoop",
        InheritFrom = "BlinkTrailFxLoop",
        AddColor = true,
        Red = 0.6,
		Green = 0.6,
		Blue = 0,
        ChainTo = "ChronosBlinkTrailFxOut",
    })

    table.insert(data.Animations,
    {
        Name = "ChronosBlinkTrailFxIn",
        InheritFrom = "BlinkTrailFxIn",
        ChainTo = "ChronosBlinkTrailFxLoop",
        StartRed = 1,
        StartGreen = 1,
        StartBlue = 0.8,
        EndRed = 0.6,
        EndGreen = 0.6,
        EndBlue = 0.0,
    })
    --Chronos Special
    table.insert(data.Animations,
    {
		Name = "Player_Chronos_GrindFire1",
		InheritFrom = "EnemyChronosBaseAnimation",
		GrannyAnimation = "Chronos_Base_ScytheGrindLoop_C_00",
		OwnerNoInvulnerableCoverage = false,
        ChainTo = "Enemy_Chronos_GrindPostFire",
		Loop = false,
		CreateAnimation = "ChronosScytheSpin",
		Sound = "/SFX/Enemy Sounds/Chronos/ChronosSuctionStartAndLoop",
		StopSoundOnFinishFade = 0.2,
	})
   --Chronos Dash
    table.insert(data.Animations,
	{
		Name = "Player_Chronos_DashFire",
		InheritFrom = "EnemyChronosBaseAnimation",
		GrannyAnimation = "Chronos_Base_DashFire_C_00",
		ChainTo = "Player_Chronos_DashPostFire",
		OwnerHasNoUnitCollision = true,
	})
    table.insert(data.Animations,
	{
		Name = "Player_Chronos_DashPostFire",
		InheritFrom = "EnemyChronosBaseAnimation",
		GrannyAnimation = "Chronos_Base_DashReturnToIdle_C_00",
		ChainTo = "NPC_Chronos_Enlightened_Hover",
		HoldLastFrame = false,
	})

    table.insert(data.Animations,
    {
      Name = "HadesOneDemeterRushProjectileHead",
      Type = "Book",
      FilePath = "JarlUlsfark-MelinoeCallsForAid\\Fx\\DemeterSmokeDirectional\\DemeterSmokeDirectional",
      NumFrames = 43,
      PlaySpeed = 60,
      Material = "Unlit",
      Scale = 1.5,
      AngleFromOwner = "Maintain",
      UseOwnAngle = true,
      SortMode = "FromParent",
      Sound = "/SFX/Player Sounds/DemeterColdNovaRush",
      StartRed = 1,
      StartGreen = 1,
      StartBlue = 1,
      EndRed = 0,
      EndGreen = 0,
      EndBlue = 0,
      AddColor = true,
      EaseIn = 0.9,
      EaseOut = 1.0,
      VisualFxDistanceMin = 30,
      VisualFxDistanceMax = 40,
      VisualFxCap = 16,
      --VisualFx = "DemeterRushProjectileTrail",
    })

    table.insert(data.Animations,
    {
      Name = "HadesOneDemeterRushProjectileImpactFx",
      Type = "Slide",
      FilePath = "JarlUlsfark-MelinoeCallsForAid\\Fx\\DemeterSmokeA\\DemeterSmokeA",
      NumFrames = 47,
      Material = "Unlit",
      StartScale = 0.7,
      EndScale = 0.69,
      DieWithOwner = false,
      ColorFromOwner = "Ignore",
      ScaleFromOwner = "Ignore",
      AngleFromOwner = "Ignore",
      UseAttachedFlasher = false,
      OverlayVfx = true,
	    UseOwnAngle = false,
      Sound = "/SFX/Player Sounds/DemeterRushImpactPoof",
      CreateAnimation = "QuickFlashIce",
      Slides = {
        { DurationFrames = 1 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
        { DurationFrames = 0 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
        { DurationFrames = 1 },
      },
    })

return data
end)

