import "Hexes/ChronosCircle/PlayerWeapons.lua"
import "Hexes/ChronosCircle/WeaponData.lua"
import "Hexes/ChronosCircle/TraitData.lua"
import "Hexes/ChronosCircle/SpellData.lua"
import "Hexes/ChronosCircle/TalentData.lua"

import "Hexes/ChronosSummon/PlayerWeapons.lua"
import "Hexes/ChronosSummon/WeaponData.lua"
import "Hexes/ChronosSummon/TraitData.lua"
import "Hexes/ChronosSummon/SpellData.lua"
import "Hexes/ChronosSummon/TalentData.lua"
import "Hexes/ChronosSummon/EnemyUnits.lua"